language: python

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - py.test tests/test_module.py --verbose --cov-report term --cov-report xml --cov imagesoup
  - codecov
