language: python

python:
  - 2.7
  - 3.6

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-pt
  - sudo locale-gen --no-purge --lang pt_BR.UTF-8
  - wget -N https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip
  - unzip https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip

install:
  - pip install -r requirements.txt

script: py.test tests/test.py --cov imagesoup

after_sucess: bash <(curl -s https://codecov.io/bash)
